-- INSERT, SEQUENCE y TRIGGER - Base de Datos HOSTALDB
--select * from TABS;


--LIMPIEZA DE BD SEQUENCES y TRIGGERS
---Ejecutar resultados...
--SELECT 'DROP SEQUENCE '||SEQUENCE_NAME||';' from ALL_SEQUENCES where SEQUENCE_OWNER='HOSTAL';
--SELECT 'DROP TRIGGER '||TRIGGER_NAME||';' from ALL_TRIGGERS where OWNER='HOSTAL';
--commit;


--AUTOINCREMENT USUARIO
CREATE SEQUENCE SEQ_USUARIO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_USUARIO
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.idUsuario FROM DUAL;
END;
/

--AUTOINCREMENT EMPRESA
CREATE SEQUENCE SEQ_EMPRESA
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_EMPRESA
BEFORE INSERT ON EMPRESA
FOR EACH ROW
BEGIN
SELECT SEQ_EMPRESA.NEXTVAL INTO :NEW.idEmpresa FROM DUAL;
END;
/

--AUTOINCREMENT EMPLEADO
CREATE SEQUENCE SEQ_EMPLEADO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_EMPLEADO
BEFORE INSERT ON EMPLEADO
FOR EACH ROW
BEGIN
SELECT SEQ_EMPLEADO.NEXTVAL INTO :NEW.idEmpleado FROM DUAL;
END;
/

--AUTOINCREMENT HUESPED
CREATE SEQUENCE SEQ_HUESPED
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_HUESPED
BEFORE INSERT ON HUESPED
FOR EACH ROW
BEGIN
SELECT SEQ_HUESPED.NEXTVAL INTO :NEW.idHuesped FROM DUAL;
END;
/

--AUTOINCREMENT HUESPED_HABITACION
CREATE SEQUENCE SEQ_HUESP_HABIT
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_HUESP_HABIT
BEFORE INSERT ON HUESPED_HABITACION
FOR EACH ROW
BEGIN
SELECT SEQ_HUESP_HABIT.NEXTVAL INTO :NEW.idHuesped_Habitacion FROM DUAL;
END;
/

/*--AUTOINCREMENT COMEDOR ELIMINADA
CREATE SEQUENCE SEQ_COMEDOR
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_COMEDOR
BEFORE INSERT ON COMEDOR
FOR EACH ROW
BEGIN
SELECT SEQ_COMEDOR.NEXTVAL INTO :NEW.idComedor FROM DUAL;
END;
*/

--AUTOINCREMENT FACTURA
CREATE  SEQUENCE SEQ_FACTURA
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_FACTURA
BEFORE INSERT ON FACTURA
FOR EACH ROW
BEGIN
SELECT SEQ_FACTURA.NEXTVAL INTO :NEW.idFactura FROM DUAL;
END;
/

--AUTOINCREMENT HABITACION
CREATE SEQUENCE SEQ_HABITACION
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_HABITACION
BEFORE INSERT ON HABITACION
FOR EACH ROW
BEGIN
SELECT SEQ_HABITACION.NEXTVAL INTO :NEW.idHabitacion FROM DUAL;
END;
/

--AUTOINCREMENT MINUTA
CREATE SEQUENCE SEQ_MINUTA
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_MINUTA
BEFORE INSERT ON MINUTA
FOR EACH ROW
BEGIN
SELECT SEQ_MINUTA.NEXTVAL INTO :NEW.idMinuta FROM DUAL;
END;
/

--AUTOINCREMENT ORDEN_COMEDOR
CREATE SEQUENCE SEQ_ORDEN_COMEDOR
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_ORDEN_COMEDOR
BEFORE INSERT ON ORDEN_COMEDOR
FOR EACH ROW
BEGIN
SELECT SEQ_ORDEN_COMEDOR.NEXTVAL INTO :NEW.idOrden_Comedor FROM DUAL;
END;
/

--AUTOINCREMENT ORDEN_COMPRA
CREATE SEQUENCE SEQ_ORDEN_COMPRA
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_ORDEN_COMPRA
BEFORE INSERT ON ORDEN_COMPRA
FOR EACH ROW
BEGIN
SELECT SEQ_ORDEN_COMPRA.NEXTVAL INTO :NEW.idOrden_Compra FROM DUAL;
END;
/

--AUTOINCREMENT ORDEN_HABITACION -- ELIMINADA
/*CREATE SEQUENCE SEQ_ORDEN_HABITACION
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_ORDEN_HABITACION
BEFORE INSERT ON ORDEN_HABITACION
FOR EACH ROW
BEGIN
SELECT SEQ_ORDEN_HABITACION.NEXTVAL INTO :NEW.idOrden_Habitacion FROM DUAL;
END;
*/

--AUTOINCREMENT ORDEN_PEDIDO
CREATE SEQUENCE SEQ_ORDEN_PEDIDO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_ORDEN_PEDIDO
BEFORE INSERT ON ORDEN_PEDIDO
FOR EACH ROW
BEGIN
SELECT SEQ_ORDEN_PEDIDO.NEXTVAL INTO :NEW.idOrden_Pedido FROM DUAL;
END;
/

--AUTOINCREMENT PLATO
CREATE SEQUENCE SEQ_PLATO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_PLATO
BEFORE INSERT ON PLATO
FOR EACH ROW
BEGIN
SELECT SEQ_PLATO.NEXTVAL INTO :NEW.idPlato FROM DUAL;
END;
/

--AUTOINCREMENT PRODUCTO
CREATE SEQUENCE SEQ_PRODUCTO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_PRODUCTO
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_PRODUCTO.NEXTVAL INTO :NEW.idProducto FROM DUAL;
END;
/

--AUTOINCREMENT PROVEEDOR
CREATE SEQUENCE SEQ_PROVEEDOR
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_PROVEEDOR
BEFORE INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
SELECT SEQ_PROVEEDOR.NEXTVAL INTO :NEW.idProveedor FROM DUAL;
END;
/

--AUTOINCREMENT RECEPCION_PRODUCTO
CREATE SEQUENCE SEQ_RECEPCION_PROD
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_RECEPCION_PROD
BEFORE INSERT ON RECEPCION_PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_RECEPCION_PROD.NEXTVAL INTO :NEW.idRecepcion_Producto FROM DUAL;
END;
/

--AUTOINCREMENT SERVICIO
CREATE SEQUENCE SEQ_SERVICIO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_SERVICIO
BEFORE INSERT ON SERVICIO
FOR EACH ROW
BEGIN
SELECT SEQ_SERVICIO.NEXTVAL INTO :NEW.idServicio FROM DUAL;
END;
/
commit;

--AUTOINCREMENT FECHA RESERVAS
CREATE SEQUENCE SEQ_FECHAS_RESERVAS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRIG_FECHAS_RESERVAS
BEFORE INSERT ON FECHAS_RESERVAS
FOR EACH ROW
BEGIN
SELECT SEQ_FECHAS_RESERVAS.NEXTVAL INTO :NEW.IDFECHA_RESERVAS FROM DUAL;
END;
/
commit;