//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public decimal IDFACTURA { get; set; }
        public decimal NRO_FACTURA { get; set; }
        public Nullable<decimal> ORDEN_COMPRA_ID { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
    }
}
