//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABITACION()
        {
            this.HUESPED_HABITACION = new HashSet<HUESPED_HABITACION>();
            this.ORDEN_HABITACION = new HashSet<ORDEN_HABITACION>();
        }
    
        public decimal IDHABITACION { get; set; }
        public string TIPO_CAMA { get; set; }
        public string ACCESORIO { get; set; }
        public decimal PRECIO { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> ESTADO_HABITACION_ID { get; set; }
    
        public virtual ESTADO_HABITACION ESTADO_HABITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HUESPED_HABITACION> HUESPED_HABITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_HABITACION> ORDEN_HABITACION { get; set; }
    }
}
