//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUESPED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HUESPED()
        {
            this.HUESPED_HABITACION = new HashSet<HUESPED_HABITACION>();
        }
    
        public decimal IDHUESPED { get; set; }
        public decimal RUT { get; set; }
        public string DV { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public decimal TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string CARGO { get; set; }
        public Nullable<decimal> EMPRESA_ID { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HUESPED_HABITACION> HUESPED_HABITACION { get; set; }
    }
}
