//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesHostal : DbContext
    {
        public EntitiesHostal()
            : base("name=EntitiesHostal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMEDOR> COMEDOR { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ESTADO_HABITACION> ESTADO_HABITACION { get; set; }
        public virtual DbSet<ESTADO_ORDEN_PEDIDO> ESTADO_ORDEN_PEDIDO { get; set; }
        public virtual DbSet<ESTADO_RECEPCION> ESTADO_RECEPCION { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
        public virtual DbSet<HABITACION> HABITACION { get; set; }
        public virtual DbSet<HUESPED> HUESPED { get; set; }
        public virtual DbSet<HUESPED_HABITACION> HUESPED_HABITACION { get; set; }
        public virtual DbSet<MINUTA> MINUTA { get; set; }
        public virtual DbSet<ORDEN_COMEDOR> ORDEN_COMEDOR { get; set; }
        public virtual DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual DbSet<ORDEN_HABITACION> ORDEN_HABITACION { get; set; }
        public virtual DbSet<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
        public virtual DbSet<PLATO> PLATO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RECEPCION_PRODUCTO> RECEPCION_PRODUCTO { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
