//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_HABITACION
    {
        public decimal IDORDEN_HABITACION { get; set; }
        public Nullable<decimal> HABITACION_ID { get; set; }
        public Nullable<decimal> ORDEN_COMPRA_ID { get; set; }
    
        public virtual HABITACION HABITACION { get; set; }
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
    }
}
