//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION_PRODUCTO
    {
        public decimal IDRECEPCION_PRODUCTO { get; set; }
        public decimal NRO_RECEPCION { get; set; }
        public decimal CODIGO_BARRA { get; set; }
        public Nullable<decimal> PRODUCTO_ID { get; set; }
        public Nullable<decimal> ESTADO_RECEPCION_ID { get; set; }
        public Nullable<decimal> ORDEN_PEDIDO_ID { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual ESTADO_RECEPCION ESTADO_RECEPCION { get; set; }
        public virtual ORDEN_PEDIDO ORDEN_PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
